# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classificar_nota.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #ffccec;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 170, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_nota = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nota.setGeometry(QtCore.QRect(400, 180, 311, 31))
        self.lineEdit_nota.setStyleSheet("background-color: #ffffff;")
        self.lineEdit_nota.setObjectName("lineEdit_nota")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(20, 310, 591, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_resultado.setFont(font)
        self.label_resultado.setObjectName("label_resultado")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 30, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 141, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Downloads/𝙲𝚁𝙴_ 巴辣辣.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_classificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_classificar.setGeometry(QtCore.QRect(340, 240, 75, 23))
        self.pushButton_classificar.setStyleSheet("background-color: #ffffff;")
        self.pushButton_classificar.setObjectName("pushButton_classificar")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(650, 300, 131, 101))
        self.label_imagem.setScaledContents(True)
        self.label_imagem.setObjectName("label_imagem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Digite sua nota:  "))
        self.label_resultado.setText(_translate("MainWindow", "Resultado:"))
        self.label_3.setText(_translate("MainWindow", "Desempenho do aluno "))
        self.pushButton_classificar.setText(_translate("MainWindow", "Enviar"))
        self.label_imagem.setText(_translate("MainWindow", "TextLabel"))
